import type { IntentListResponse } from '../../services/intentApi';

const now = '2026-06-28T18:04:00.000Z';

export const INTENT_MOCK: IntentListResponse = {
  total: 4,
  confirmed: 1,
  candidates: 3,
  rejected: 0,
  holds: 2,
  broken: 1,
  personas: [
    {
      id: 'p1',
      name: 'Developer',
      emoji: '🧑‍💻',
      description: 'Builds and ships the app',
      confirmed: false,
      candidateCount: 3,
      confirmedCount: 1,
      rejectedCount: 0,
      holdsCount: 2,
      brokenCount: 1,
      jobs: [
        {
          id: 'j1',
          title: 'Understand a codebase',
          priority: 'high',
          confirmed: false,
          candidateCount: 2,
          confirmedCount: 1,
          rejectedCount: 0,
          holdsCount: 2,
          brokenCount: 1,
          statements: [
            {
              id: 'stmt-1',
              text: 'Repo analysis reads real files via the GitHub API without cloning locally.',
              kind: 'behavior',
              status: 'candidate',
              source: 'inferred',
              featureArea: 'Understand a codebase',
              scope: 'job',
              links: [{ filePath: 'app/server/services/analyzer.js', symbol: 'analyzeRepo', linkStatus: 'healthy' }],
              satisfied: true,
              lastCheckedAt: now,
              createdAt: now,
              updatedAt: null,
            },
            {
              id: 'stmt-2',
              text: 'Analysis results persist so revisiting a project does not re-fetch everything.',
              kind: 'constraint',
              status: 'candidate',
              source: 'inferred',
              featureArea: 'Understand a codebase',
              scope: 'job',
              links: [{ filePath: 'app/server/lib/db.js', symbol: 'deployments', linkStatus: 'healthy' }],
              satisfied: false,
              lastCheckedAt: now,
              createdAt: now,
              updatedAt: null,
            },
            {
              id: 'stmt-3',
              text: 'Authenticated routes reject requests without a valid session.',
              kind: 'behavior',
              status: 'confirmed',
              source: 'human',
              featureArea: 'Understand a codebase',
              scope: 'job',
              links: [{ filePath: 'app/server/middleware/requireAuth.js', symbol: 'requireAuth', linkStatus: 'healthy' }],
              satisfied: true,
              lastCheckedAt: now,
              createdAt: now,
              updatedAt: now,
            },
          ],
        },
      ],
    },
  ],
  globals: {
    title: 'Security & safety basics',
    candidateCount: 0,
    confirmedCount: 0,
    rejectedCount: 0,
    holdsCount: 0,
    brokenCount: 0,
    statements: [],
  },
};
