import { useCallback, useEffect, useState } from 'react';
import { AlertTriangle, Loader2, RefreshCw, X } from 'lucide-react';
import { reanalyzeProject } from '../../services/api';
import { ApiError } from '../../lib/api-error';

export interface ReanalyzeModalProps {
  open: boolean;
  onClose: () => void;
  projectId: string;
  /** What the user sees in the headline — e.g. "owner/repo". */
  projectLabel: string;
  /** Called after the POST succeeds, with the projectId. The caller
   *  is responsible for navigation (usually to `/takeoff/:id`). */
  onTriggered: (projectId: string) => void;
}

// Confirmation modal for re-analyzing an existing project. Two reasons
// it's not a `window.confirm`:
//   1. Re-analyze regenerates the plan, which loses any user todo/done
//      checkoffs the user made on plan_steps. The native dialog can't
//      explain this nuance.
//   2. The action is async (POST) and can fail with 409 (already
//      analyzing) or 400 (uploaded folder, no GitHub URL). The user
//      needs to see those error messages and be able to retry.
//
// The "preserved" / "reset" breakdown mirrors the server-side
// snapshot/restore contract in `runPipeline`:
//   PRESERVED: v2 gap triage, reject reasons, refined prompts,
//              shipped→commit links, build story entries, product map
//   RESET:     plan-step checkoffs (regenerated), context files
//              (regenerated by design), the analysis itself
export function ReanalyzeModal({
  open, onClose, projectId, projectLabel, onTriggered,
}: ReanalyzeModalProps) {
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Reset internal state every time the modal re-opens. Otherwise a
  // failed attempt leaves a stale error pinned even after the user
  // closes + retries.
  useEffect(() => {
    if (open) {
      setError(null);
      setSubmitting(false);
    }
  }, [open]);

  // ESC to close — only while open, removed on unmount. Mirrors the
  // ShareSecurityModal pattern so the two feel consistent.
  useEffect(() => {
    if (!open) return;
    function onKey(e: KeyboardEvent) {
      if (e.key === 'Escape' && !submitting) onClose();
    }
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [open, onClose, submitting]);

  const handleConfirm = useCallback(async () => {
    setSubmitting(true);
    setError(null);
    try {
      const result = await reanalyzeProject(projectId);
      onTriggered(result.projectId);
    } catch (err) {
      if (err instanceof ApiError) setError(err.message);
      else setError(err instanceof Error ? err.message : 'Failed to start re-analysis');
      setSubmitting(false);
    }
  }, [projectId, onTriggered]);

  if (!open) return null;

  return (
    <div
      role="dialog"
      aria-modal="true"
      aria-labelledby="reanalyze-title"
      className="fixed inset-0 z-50 flex items-center justify-center px-4 py-8"
    >
      <div
        className="absolute inset-0 bg-stone-900/40 backdrop-blur-sm"
        onClick={submitting ? undefined : onClose}
        aria-hidden
      />
      <div className="relative bg-white border border-stone-200 rounded-lg shadow-xl w-full max-w-md max-h-full overflow-y-auto">
        <div className="flex items-start justify-between p-5 border-b border-stone-100">
          <div className="flex items-start gap-3 min-w-0">
            <div className="w-9 h-9 rounded bg-stone-900 text-white flex items-center justify-center flex-shrink-0">
              <RefreshCw className="w-4 h-4" strokeWidth={2.5} aria-hidden />
            </div>
            <div className="min-w-0">
              <h2 id="reanalyze-title" className="text-base font-bold text-stone-900 tracking-tight">
                Re-analyze this project?
              </h2>
              <p className="text-xs text-stone-500 mt-0.5 truncate" title={projectLabel}>
                {projectLabel}
              </p>
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            disabled={submitting}
            aria-label="Close"
            className="text-stone-400 hover:text-stone-700 transition-colors p-1 -m-1 disabled:opacity-50"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        <div className="p-5 space-y-4 text-sm">
          <p className="text-stone-700 leading-relaxed">
            We&rsquo;ll re-scan the repo and refresh the readiness score, stack detection,
            security report, gaps, and AI-ready context files.
          </p>

          <div className="bg-stone-50 border border-stone-200 rounded-md p-3 space-y-2">
            <p className="text-xs uppercase tracking-wider font-semibold text-stone-700">
              Your work is preserved
            </p>
            <ul className="text-xs text-stone-600 space-y-1 list-disc list-inside marker:text-stone-400">
              <li>Gap triage (accepted, rejected, in progress, shipped)</li>
              <li>Reject reasons and refined prompts</li>
              <li>Shipped commits and their gap links</li>
              <li>Build Story entries</li>
              <li>Product map (personas, jobs, edits)</li>
            </ul>
          </div>

          <div className="bg-amber-50 border border-amber-200 rounded-md p-3 space-y-2">
            <p className="text-xs uppercase tracking-wider font-semibold text-amber-800 inline-flex items-center gap-1.5">
              <AlertTriangle className="w-3.5 h-3.5" aria-hidden />
              Resets
            </p>
            <ul className="text-xs text-amber-800 space-y-1 list-disc list-inside marker:text-amber-500">
              <li>Plan-step checkoffs (the plan is regenerated)</li>
              <li>AI-ready context files (regenerated from the new analysis)</li>
            </ul>
          </div>

          {error ? (
            <p className="flex items-start gap-1.5 text-xs text-red-700 bg-red-50 border border-red-200 rounded px-2.5 py-2">
              <AlertTriangle className="w-3.5 h-3.5 mt-0.5 flex-shrink-0" aria-hidden />
              <span>{error}</span>
            </p>
          ) : null}
        </div>

        <div className="flex items-center justify-end gap-2 px-5 py-3 border-t border-stone-100 bg-stone-50/50">
          <button
            type="button"
            onClick={onClose}
            disabled={submitting}
            className="px-3 py-1.5 text-sm font-medium text-stone-700 hover:text-stone-900 rounded transition-colors disabled:opacity-50"
          >
            Cancel
          </button>
          <button
            type="button"
            onClick={handleConfirm}
            disabled={submitting}
            className="inline-flex items-center gap-1.5 px-4 py-1.5 text-sm font-medium text-white bg-stone-900 hover:bg-stone-800 disabled:bg-stone-400 disabled:cursor-not-allowed rounded transition-colors"
          >
            {submitting ? (
              <>
                <Loader2 className="w-3.5 h-3.5 animate-spin" aria-hidden />
                Starting…
              </>
            ) : (
              <>
                <RefreshCw className="w-3.5 h-3.5" aria-hidden />
                Re-analyze now
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
}

export default ReanalyzeModal;
